### PR TITLE
styles for VideoModal

### PR DESCRIPTION
**Pull request by imxande**

### CODE REVIEW

**Comment by traviscollins** [comment]
I noticed all these renaming. They're good... but one problem. All of the style files are named "style.js". This makes it difficult to know which style.js you're working on (searching code, finding references, etc). 

Can you change them to be something {componentName}-style.js?

**Comment by ArianaShackelford** [comment]
@traviscollins  Would you like us to rename the index.js file in each component folder to {componentName}-index.jsx as well?

**Comment by jason-glassbrook** [comment]
@traviscollins On the `restructure-components` branch, I can rename things with a script so it's all in one place. I guess it can be confusing if your IDE doesn't show the breadcrumbs... What if we rename things like the following?

```
<component>/
    index.<ext> -- retain for exports
    <component>.<ext>
    <component>.style.<ext>
    <component>.test.<ext>
```

**Comment by traviscollins** [comment]
Yes. Or you can rename them just {componentName}.jsx

**Pull request merged**
