### PR TITLE
Fix import linting

### PR DESCRIPTION
**Pull request by jason-glassbrook**
Fix false linting errors/warnings caused by:

- interoperation between JS and TS
- packages that perform exports dynamically, so static analysis cannot work

Remove unnecessary (and error-prone) use of extensions for imports from some `js`, `jsx`, `ts`, `tsx` files.

> NOTE: The `fix-import-linting` branch can be safely deleted after merging.

### CODE REVIEW

**Comment by traviscollins** [comment]
@jason-glassbrook @ccannell reports that this branch has several issues related the layout of the UI, and some component errors after login. However, Chris is starting his work on refactoring the API access code to use the Apollo GraphQL server off of master. He's going to start working on master today. 

Can you give us a summary of what this branch is trying to accomplish, and whether we should import it or abandon? 

Thanks again for all your help!

**Comment by jason-glassbrook** [comment]
@traviscollins @ccannell The purpose of this branch to update the linting configuration so that it stops reporting that certain files do not exist when you try to import from them. It's not a super high priority, but it was an annoyance that I figured I'd fix.

By default, the linter is configured to only consider `.js` files, so it would warn that paths could not be resolved when importing from a `.jsx` or `.tsx` files. To get around this (now, and prior to me updating the linting config early on), many imports included the file extensions to "force" the linter to "see" those other files. However, as you convert the app from JS to TS, including the file extensions in imports could be problematic, because you'll both have to convert the source file to TS and update any imports of it that happen to include the old file extension.

@ccannell I'm curious what UI and component errors you're encountering because I only changed the linter config (no runtime interactions) and removed extraneous file extensions in imports. Layout-wise, this branch should be equivalent to `master`. I can only imagine that there's some stray file that has both a `.js(x)` and a `.ts(x)` version and that Expo is defaulting to compiling the older `.js(x)` one...

@traviscollins I cannot get past the login screen anymore to check anything, so I'm guessing that I've been removed from the list of authorized users.

**Comment by traviscollins** [comment]
Thanks Jason. Seems reasonable. 

I checked out this branch and found that it was working for me. Chris is trying one more time. 

The backend for staging has now been replaced with the new Apollo GraphQL service, and the old DJango Python based API is gone. So the app isn’t working, because none of it’s expected endpoints work anymore. Chris is working on replacing the API calls in the app to use the new backend.

**Comment by ccannell** [comment]
If there are no objections, I'm going to merge this. The changes I am making are based off this branch. My changes are touching everything.

**Pull request merged**
